CREATE TABLE cars
(
    make varchar(10)
)

INSERT INTO cars
VALUES('HONDA');
INSERT INTO cars
VALUES('HONDA');
INSERT INTO cars
VALUES('TOYOTA');
INSERT INTO cars
VALUES('TOYOTA');
INSERT INTO cars
VALUES('NISSAN');